package com.thecodevillage.hostelreserveapp.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.thecodevillage.hostelreserveapp.db.Hostel;
import com.thecodevillage.hostelreserveapp.db.Room;

import com.thecodevillage.hostelreserveapp.db.HostelDao;
import com.thecodevillage.hostelreserveapp.db.RoomDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig hostelDaoConfig;
    private final DaoConfig roomDaoConfig;

    private final HostelDao hostelDao;
    private final RoomDao roomDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        hostelDaoConfig = daoConfigMap.get(HostelDao.class).clone();
        hostelDaoConfig.initIdentityScope(type);

        roomDaoConfig = daoConfigMap.get(RoomDao.class).clone();
        roomDaoConfig.initIdentityScope(type);

        hostelDao = new HostelDao(hostelDaoConfig, this);
        roomDao = new RoomDao(roomDaoConfig, this);

        registerDao(Hostel.class, hostelDao);
        registerDao(Room.class, roomDao);
    }
    
    public void clear() {
        hostelDaoConfig.clearIdentityScope();
        roomDaoConfig.clearIdentityScope();
    }

    public HostelDao getHostelDao() {
        return hostelDao;
    }

    public RoomDao getRoomDao() {
        return roomDao;
    }

}
